General:
  oc_implementation: 'hinge'
  gravnet:
    - n: 64
    - n: 64
  n_cluster_space_coordinates: 3
  n_gravnet_space_coordinates: 3
  fix_distance: 1

DenseOptions:
  activation: "elu"
  kernel_regularizer_rate: 0.00000000001
  dropout: 0.000001

BatchNormOptions:
  max_viscosity: 0.5
  learn: True

LossOptions:
  energy_loss_weight: 0.00000000001
  q_min: 2.1
  use_average_cc_pos: 0.99999
  classification_loss_weight: 0.00000000001
  too_much_beta_scale: 0.0
  position_loss_weight: 0.00000000001
  timing_loss_weight: 0.00000000001
  beta_loss_scale: 1.0


Training:
  - stage_1:
    batch_size: 120000
    learning_rate: 0.0005
    epochs: 1


